name: wuchuheng_imap_cache
description: wuchuheng_imap_cache is a data-driven caching library based on the IMAP protocol.
version: 1.0.18
homepage: https://github.com/wuchuheng/imap_cache_dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  intl: ^0.17.0
  enough_mail: ^2.1.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  crypto: ^3.0.2
  wuchuheng_logger: ^1.0.5
  rxdart: ^0.27.5
  wuchuheng_isolate_channel: ^0.0.18
  wuchuheng_hooks: ^0.0.7
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  sqlite3: ^1.9.1
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  wuchuheng_env: ^1.0.2
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
