name: imap_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  intl: ^0.17.0
  enough_mail: ^2.1.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  path_provider: ^2.0.11

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
