name: imap_cache
description: imap_cache is a data-driven caching library based on the IMAP protocol.
version: 0.0.12
homepage: https://github.com/wuchuheng/imap_cache_dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  intl: ^0.17.0
  enough_mail: ^2.1.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  crypto: ^3.0.2
  sqlite3: ^1.7.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
