name: wuchuheng_imap_cache
description: wuchuheng_imap_cache is a data-driven caching library based on the IMAP protocol.
version: 1.0.2
homepage: https://github.com/wuchuheng/imap_cache_dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  intl: ^0.17.0
  enough_mail: ^2.1.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  crypto: ^3.0.2
  sqlite3: ^1.7.2
  wuchuheng_logger: ^1.0.3
  rxdart: ^0.27.5
  wuchuheng_isolate_channel: ^0.0.8
  wuchuheng_hooks: ^0.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  wuchuheng_env: ^1.0.2
